import Banner from "./components/Banner";
import Navigation from "./components/navigation";
import "./globals.css";

export const metadata = {
  title: "TGM",
  description: " A site generated by create next app",
  icons: {
    icon: "/images/grass.png", // Path to your favicon file in the public directory
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Banner />
        <Navigation />
        {children}
      </body>
    </html>
  );
}

// Banner and Nav will be a part of all pages so we added in layout.js
